//! The corpus generator's randomness, pinned here rather than borrowed.
//!
//! A parity harness that generates its own corpus is only worth running if the corpus is a
//! function of the seed and nothing else — otherwise a green run proves nothing about the red one
//! yesterday. The Python this replaces got that from `random.Random(seed)`, whose exact stream is
//! a `CPython` implementation detail this port cannot reproduce and should not try to: seed
//! 20260724 generates a DIFFERENT ten thousand screens here than it did there.
//!
//! That is fine, and it is why the generator is written out instead of taken as a dependency. What
//! the harness needs is that the stream is fixed by THIS file, so a corpus can be re-generated by
//! anyone holding the seed — not that it matches a stream nothing else in the tree ever saw.
//!
//! `SplitMix64`, which is the generator `SeedSequence` and `xoshiro` both use to expand a seed,
//! used directly. It is eleven lines, has no state to get wrong, and passes the statistical bar a
//! fuzz corpus needs several times over.

/// A seeded stream of screens' worth of choices.
#[derive(Debug, Clone)]
#[expect(missing_copy_implementations, reason = "a copied generator forks the stream")]
pub struct Rng {
    state: u64,
}

/// `SplitMix64`'s increment — the odd 64-bit approximation of φ⁻¹·2⁶⁴.
const GAMMA: u64 = 0x9E37_79B9_7F4A_7C15;

/// The bottom 64 bits of a 128-bit product — Lemire's fractional part.
///
/// A written-out mask rather than an `as u64`: the truncation IS the operation here, and a cast
/// that means it reads the same as one that forgot.
const fn low_half(wide: u128) -> u64 {
    (wide & 0xFFFF_FFFF_FFFF_FFFF) as u64
}

/// The top 64 bits of a 128-bit product — Lemire's integer part, always in range by construction.
const fn high_half(wide: u128) -> u64 {
    ((wide >> 64) & 0xFFFF_FFFF_FFFF_FFFF) as u64
}

impl Rng {
    /// A stream fixed by `seed`.
    #[must_use]
    pub const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// The next 64 bits.
    pub const fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(GAMMA);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform in `0..bound`, or `0` when the range is empty.
    ///
    /// Lemire's multiply-shift with the rejection loop kept. The modulo-bias shortcut would be
    /// invisible at these bounds — every one of them is under twenty — but a corpus generator that
    /// is subtly non-uniform is a corpus generator whose coverage claim is subtly false, and the
    /// rejection almost never fires.
    pub const fn below(&mut self, bound: u64) -> u64 {
        if bound == 0 {
            return 0;
        }
        let mut wide = (self.next_u64() as u128) * (bound as u128);
        let mut low = low_half(wide);
        if low < bound {
            let threshold = bound.wrapping_neg() % bound;
            while low < threshold {
                wide = (self.next_u64() as u128) * (bound as u128);
                low = low_half(wide);
            }
        }
        high_half(wide)
    }

    /// Uniform in `low..=high`, inclusive at both ends.
    pub const fn between(&mut self, low: u64, high: u64) -> u64 {
        if high <= low {
            return low;
        }
        low + self.below(high - low + 1)
    }

    /// A valid index into a slice of `len`, or `None` when it is empty.
    pub fn index(&mut self, len: usize) -> Option<usize> {
        if len == 0 {
            return None;
        }
        let bound = u64::try_from(len).unwrap_or(u64::MAX);
        usize::try_from(self.below(bound)).ok()
    }

    /// One element, or `None` from an empty slice.
    pub fn choice<'a, T>(&mut self, items: &'a [T]) -> Option<&'a T> {
        self.index(items.len()).and_then(|at| items.get(at))
    }

    /// `count` DISTINCT elements, in the order the draw produced them.
    ///
    /// A partial Fisher–Yates over a copy of the index space, which is what makes it
    /// without-replacement rather than a retry loop that can spin. Fewer than `count` elements
    /// available means all of them, shuffled — the caller asked for a sample, not a guarantee.
    pub fn sample<T: Clone>(&mut self, items: &[T], count: usize) -> Vec<T> {
        let mut order: Vec<usize> = (0..items.len()).collect();
        let wanted = count.min(items.len());
        let mut drawn = Vec::with_capacity(wanted);
        for position in 0..wanted {
            let remaining = order.len() - position;
            let Some(offset) = self.index(remaining) else {
                break;
            };
            order.swap(position, position + offset);
            if let Some(picked) = order.get(position).and_then(|at| items.get(*at)) {
                drawn.push(picked.clone());
            }
        }
        drawn
    }
}

#[cfg(test)]
mod tests {
    use super::Rng;

    /// The property the whole harness rests on: same seed, same corpus.
    #[test]
    fn a_seed_fixes_the_stream() {
        let mut first = Rng::new(20_260_724);
        let mut second = Rng::new(20_260_724);
        let mine: Vec<u64> = (0..64).map(|_| first.next_u64()).collect();
        let yours: Vec<u64> = (0..64).map(|_| second.next_u64()).collect();
        assert_eq!(mine, yours);
        assert_ne!(mine, (0..64).map(|_| Rng::new(1).next_u64()).collect::<Vec<_>>());
    }

    #[test]
    fn a_bound_is_never_exceeded() {
        let mut rng = Rng::new(7);
        for bound in 1..=20 {
            for _ in 0..200 {
                assert!(rng.below(bound) < bound);
            }
        }
        assert_eq!(rng.below(0), 0);
        assert_eq!(rng.below(1), 0);
    }

    #[test]
    fn an_inclusive_range_reaches_both_ends() {
        let mut rng = Rng::new(11);
        let drawn: Vec<u64> = (0..500).map(|_| rng.between(1, 8)).collect();
        assert!(drawn.iter().all(|value| (1..=8).contains(value)));
        assert!(drawn.contains(&1) && drawn.contains(&8));
        assert_eq!(rng.between(5, 5), 5);
        assert_eq!(rng.between(9, 2), 9);
    }

    /// Without replacement, which a retry loop would only approximate.
    #[test]
    fn a_sample_never_repeats_an_element() {
        let pool: Vec<u32> = (0..10).collect();
        let mut rng = Rng::new(3);
        for _ in 0..200 {
            let drawn = rng.sample(&pool, 3);
            assert_eq!(drawn.len(), 3);
            let mut unique = drawn.clone();
            unique.sort_unstable();
            unique.dedup();
            assert_eq!(unique.len(), 3);
        }
        assert_eq!(rng.sample(&pool, 99).len(), pool.len());
        assert!(rng.sample::<u32>(&[], 2).is_empty());
    }
}
