// slopdesk_ffi.h — the C ABI Swift calls into.
//
// Generated by hand, deliberately: cbindgen would have to run somewhere, and "somewhere" is either
// inside `swift build` (forbidden — cargo may not run there) or in a step that can silently not
// have run. A header a reviewer diffs against `src/lib.rs` is the cheaper guarantee, and
// `slopdesk-devtools`' FFI gate (`just ffi`) checks that every symbol declared here is present in
// every slice it assembles — and that every slice exports nothing this does not declare — so a
// header that drifts from the library fails the build rather than the app.
//
// THE CALLING CONVENTION (identical for every entry point):
//   inputs   — zero or more (const uint8_t *ptr, size_t len) pairs; a NULL pointer means empty.
//   output   — one (uint8_t *out, size_t cap) pair; out may be NULL when cap is 0.
//   returns  — how many bytes the answer NEEDS.
//                0        : there is no answer (the Rust `Option::None`).
//                n <= cap : out[0..n] holds the answer.
//                n >  cap : NOTHING was written; call again with at least n bytes.
//
// No allocation crosses this boundary in either direction, so there is nothing to free. Passing
// (NULL, 0) as the output is the supported way to ask for the length before allocating.
//
// THE HANDLE CONVENTION (SlopDeskBlockStore, SlopDeskVideoPacketizer, SlopDeskVideoReassembler,
//                        SlopDeskHostVitalsSampler, SlopDeskDisplayWake,
//                        SlopDeskLineAssembler, SlopDeskRepoWatch, SlopDeskKeyRepeat)
//   Three things cannot cross per call: memory too big to copy, a counter two sides would then
//   have to agree about who advanced, and a SYSTEM RESOURCE that has to be let go of exactly once.
//   A replay buffer is the first — up to 256 MiB of retained PTY output, appended per PTY chunk;
//   the packetizer's streamSeq/frameID are the second, and the vitals sampler's CPU baseline is the
//   same shape (a snapshot the NEXT call is measured against, which is a rule rather than a
//   number). The display-wake driver is the third: it owns an IOPMAssertion whose create must be
//   balanced by exactly one release, so the id never crosses at all and _free is what lets go.
//   Rust owns all of them; the caller holds an opaque token.
//     * exactly one _free per _new; NULL is inert everywhere.
//     * NO TWO CALLS ON ONE HANDLE MAY OVERLAP — the mutators take &mut, so a concurrent call is
//       aliasing UB. The Swift owner serialises under the lock it already held.
//       THREE EXCEPTIONS, each declared in its own doors rather than assumed: SlopDeskCursorSampler
//       holds its state behind locks because two threads calling it is that handle's design (the
//       pointer must keep flowing while the main thread is blocked), SlopDeskKeyRepeat does the
//       same because the main thread presses and releases while a timer queue asks what is due,
//       and SlopDeskVirtualDisplay does because the framework delivers its terminate callback on a
//       serial queue of its own that the caller does not own and cannot serialise against.
//       Nothing else may be assumed to be shareable; a handle without that note is not.
//     * answers still come back through (out, cap) -> needed. Nothing is allocated on one side and
//       freed on the other.
//   Producers fill a SLOT on the handle and return its item count; the caller then reads items out
//   one at a time. A slot holds until the next producer overwrites it.
//
// THE FILE IS SPLIT, AND THIS ONE IS THE ENTRY POINT.
//   `module.modulemap` names this header and nothing else, so this is what Swift sees and what a
//   `#include "slopdesk_ffi.h"` still resolves to. The doors themselves live in the parts below,
//   grouped by the surface they serve and each a contiguous slice of what used to be one 12 344-line
//   file. One file was a context bomb: a reader after ONE door paid for all of them, and so did
//   every tool that opens it.
//
//   The parts are ORDERED, not interchangeable: a typedef is declared before the doors that take it,
//   the way it was when they were one file, so the include list below is the file's old top-to-bottom
//   reading. A part is self-contained — its own guard, its own `extern "C"` — so it also compiles
//   alone, but nothing includes one directly and nothing should.
//
//   Two readers follow these `#include` lines rather than globbing the directory, and both fail loudly
//   on a part this list forgets: `slopdesk-devtools`' FFI gate, which checks the declared/exported
//   symbol bijection per slice, and `slopdesk-invariants`' tree, which hands every rule that asks for
//   this path the whole translation unit.

#ifndef SLOPDESK_FFI_H
#define SLOPDESK_FFI_H

#include "slopdesk_ffi_text.h"
#include "slopdesk_ffi_chrome.h"
#include "slopdesk_ffi_config.h"
#include "slopdesk_ffi_document.h"
#include "slopdesk_ffi_video_fec.h"
#include "slopdesk_ffi_terminal.h"
#include "slopdesk_ffi_terminal_input.h"
#include "slopdesk_ffi_video_client.h"
#include "slopdesk_ffi_video_input.h"
#include "slopdesk_ffi_video_transport.h"
#include "slopdesk_ffi_mux.h"
#include "slopdesk_ffi_host_session.h"
#include "slopdesk_ffi_device_panel.h"
#include "slopdesk_ffi_macos.h"
#include "slopdesk_ffi_reading.h"
#include "slopdesk_ffi_workspace.h"

#endif /* SLOPDESK_FFI_H */
