#!/usr/bin/env bash
# Golden regression pin (single-impl Swift, post-Rust-removal).
#
# The wire corpus `golden/golden_vectors.json` is the FROZEN source of truth for every codec's
# exact bytes. `slopdesk-corevectors` regenerates the emitted subset from the live native-Swift
# codecs; this script asserts they are byte-identical to the committed corpus.
#
# THE KEY SETS ARE PINNED, NOT INFERRED. Both buckets below are exact: the generator must emit
# EXACTLY `EMITTED_KEYS`, and the corpus must hold EXACTLY `EMITTED_KEYS | FROZEN_KEYS`. Deriving
# the diffed set as `corpus & regen` instead lets a key that stops being emitted slide silently
# into the un-diffed frozen bucket — the script prints one fewer emitted key and still PASSes, so a
# refactor that drops a `root["…"]` assignment while changing that codec's bytes ships a changed
# wire under a green gate. Membership drift in either direction is a hard failure naming the key.
#
# `FROZEN_KEYS` are in the corpus but NOT emitted (geometry/VD + nalu/sniffer/terminal-mode, whose
# implementations live in modules the generator does not import). They are pinned by XCTest
# instead: `HostOutputSnifferGoldenGuardTests` replays `hostOutputSniffer`'s corpus BYTES, and the
# rest pin BEHAVIOUR (`NALUnitTests`, `VirtualDisplayGeometryTests`, `TerminalModeTrackerTests`,
# `InputMotionCoalescerTests`, `CaptureRegionMathTests`, …) — do NOT emit them from here without
# also proving the regenerated bytes match the committed ones.
#
# This replaces the old cross-language Rust `golden_parity` test: there is no second implementation
# to diff against anymore, so it is a regression pin, not a parity proof. To UPDATE the corpus after
# an intentional wire change, regenerate with NO SLOPDESK_* env set and merge surgically — never
# `> golden/golden_vectors.json` (that drops the frozen keys the generator doesn't emit). A NEW
# vector key must also be added to `EMITTED_KEYS` below, or this gate fails by design.
set -euo pipefail
cd "$(dirname "$0")/.."

CORPUS="golden/golden_vectors.json"
REGEN="$(mktemp -t slopdesk-golden.XXXXXX.json)"
trap 'rm -f "$REGEN"' EXIT

# The generator must resolve its compile-time-const defaults — strip any SLOPDESK_* override.
# shellcheck disable=SC2046 # intentional word-splitting builds the `-u VAR` unset-flag list
env $(env | grep '^SLOPDESK_' | cut -d= -f1 | sed 's/^/-u /' | tr '\n' ' ') \
  swift run -q slopdesk-corevectors > "${REGEN}"

python3 - "${CORPUS}" "${REGEN}" << 'PY'
import json, sys

# Every key `slopdesk-corevectors` emits. Exact — a key here that the generator stops emitting, or
# a key the generator emits that is absent here, fails the gate.
EMITTED_KEYS = {
    "adaptiveGroupSize", "adaptiveTier", "audioWire", "blocksWireMessages", "coordWindowPoint",
    "cursorShape", "cursorUpdate", "fecParity", "fecRecover", "fpsGovernorEwma", "fragmentEncode",
    "inputEvent", "metadataCodecPayloads", "metadataWireMessages", "muxBare", "muxEnvelopes",
    "muxFragment", "networkEstimateFold", "owdLateDrive", "pacerDepthFloats", "pacerDepthHinted",
    "recovery", "sizeNegotiationClamp", "sizeNegotiationEpoch", "staticIdrDrive", "swipeNavStatus",
    "systemDialogClassify", "systemDialogDetect", "terminalWireMessages", "trendlineDrive",
    "udpBackoff", "udpRearm", "videoControl", "windowGeometry", "workspaceIntentArgs",
    "workspaceIntentOps", "workspaceStateCodec", "workspaceWireMessages", "ycbcr",
}

# In the corpus, NOT emitted; pinned by their own XCTest suites. See the header before touching.
FROZEN_KEYS = {
    "captureRetarget", "captureUnion", "hostOutputSniffer", "inputMotionCoalesce", "naluJoin",
    "naluSplit", "terminalModeTracker", "vdChipPixelLimit", "vdOriginToRight", "vdRefreshRates",
    "virtualDisplayGeometry", "windowFits", "windowPlacement",
}

corpus = json.load(open(sys.argv[1]))
regen = json.load(open(sys.argv[2]))
canon = lambda x: json.dumps(x, sort_keys=True, separators=(",", ":"))

failures = []


def pin(label, expected, actual, gone, new):
    """Assert an exact key set, naming BOTH drift directions."""
    missing, extra = sorted(expected - actual), sorted(actual - expected)
    if missing:
        failures.append(f"{label}: {gone}: {missing}")
    if extra:
        failures.append(f"{label}: {new}: {extra}")


# A key in both buckets would make the corpus assertion pass while excusing a dropped emission.
overlap = sorted(EMITTED_KEYS & FROZEN_KEYS)
if overlap:
    failures.append(f"pin is self-inconsistent — both emitted and frozen: {overlap}")

pin(
    "generator", EMITTED_KEYS, set(regen),
    "pinned key NO LONGER EMITTED (add the emission back, or move it to FROZEN_KEYS with an "
    "XCTest that pins its bytes)",
    "emits UNPINNED key (hand-merge it into the corpus and add it to EMITTED_KEYS)",
)
pin(
    "corpus", EMITTED_KEYS | FROZEN_KEYS, set(corpus),
    "pinned key MISSING FROM THE CORPUS (a `>`-redirect over golden_vectors.json does this)",
    "holds UNPINNED key (add it to EMITTED_KEYS or FROZEN_KEYS)",
)

# Byte-diff over the keys actually present on both sides, so a set drift reports as a set drift
# rather than a KeyError. The pin above independently guarantees this covers all of EMITTED_KEYS.
diffed = sorted(EMITTED_KEYS & set(corpus) & set(regen))
bad = [k for k in diffed if canon(corpus[k]) != canon(regen[k])]
if bad:
    failures.append(f"DIVERGED bytes ({len(bad)}): {sorted(bad)}")

print(f"golden-check: {len(diffed)} emitted keys diffed vs {sys.argv[1]}")
if failures:
    for f in failures:
        print(f"  FAIL — {f}")
    sys.exit(1)
print("  PASS — all emitted keys byte-identical")
print(f"  ({len(FROZEN_KEYS)} frozen keys are XCTest-pinned, not emitted: {sorted(FROZEN_KEYS)})")
PY
