#!/usr/bin/env bash
# Golden regression pin (single-impl Swift, post-Rust-removal).
#
# The wire corpus `golden/golden_vectors.json` is the FROZEN source of truth for every codec's
# exact bytes. `slopdesk-corevectors` regenerates the emitted subset from the live native-Swift
# codecs; this script asserts they are byte-identical to the committed corpus.
#
# THE KEY SETS ARE PINNED, NOT INFERRED. Both buckets below are exact: the generator must emit
# EXACTLY `EMITTED_KEYS`, and the corpus must hold EXACTLY `EMITTED_KEYS | FROZEN_KEYS`. Deriving
# the diffed set as `corpus & regen` instead lets a key that stops being emitted slide silently
# into the un-diffed frozen bucket — the script prints one fewer emitted key and still PASSes, so a
# refactor that drops a `root["…"]` assignment while changing that codec's bytes ships a changed
# wire under a green gate. Membership drift in either direction is a hard failure naming the key.
#
# `FROZEN_KEYS` are in the corpus but NOT emitted (geometry/VD + nalu/sniffer/terminal-mode/input,
# whose implementations live in modules the generator does not import). Each is pinned by a suite
# that REPLAYS its vectors — `*GoldenVectorTests` under `Tests/`, `golden_sniffer.rs` and
# `golden_vectors.rs` under `rust/*/tests/` — and the check at the bottom of this script enforces
# that a reader exists, because for ten of the thirteen this paragraph used to be the only
# guarantee and it was false. A suite that merely tests the same FUNCTION by hand is not a pin: it
# does not open the corpus, so the vectors can drift out from under it (see `vdRefreshRates`).
# Do NOT emit a frozen key from here without also proving the regenerated bytes match the committed
# ones.
#
# This replaces the old cross-language Rust `golden_parity` test: there is no second implementation
# to diff against anymore, so it is a regression pin, not a parity proof. To UPDATE the corpus after
# an intentional wire change, regenerate with NO SLOPDESK_* env set and merge surgically — never
# `> golden/golden_vectors.json` (that drops the frozen keys the generator doesn't emit). A NEW
# vector key must also be added to `EMITTED_KEYS` below, or this gate fails by design.
set -euo pipefail
cd "$(dirname "$0")/.."

CORPUS="golden/golden_vectors.json"
REGEN="$(mktemp -t slopdesk-golden.XXXXXX.json)"
trap 'rm -f "$REGEN"' EXIT

# The generator must resolve its compile-time-const defaults — strip any SLOPDESK_* override.
# shellcheck disable=SC2046 # intentional word-splitting builds the `-u VAR` unset-flag list
env $(env | grep '^SLOPDESK_' | cut -d= -f1 | sed 's/^/-u /' | tr '\n' ' ') \
  swift run -q slopdesk-corevectors > "${REGEN}"

FROZEN_LIST="$(mktemp -t slopdesk-frozen.XXXXXX)"
trap 'rm -f "$REGEN" "$FROZEN_LIST"' EXIT

python3 - "${CORPUS}" "${REGEN}" "${FROZEN_LIST}" << 'PY'
import json, sys

# Every key `slopdesk-corevectors` emits. Exact — a key here that the generator stops emitting, or
# a key the generator emits that is absent here, fails the gate.
EMITTED_KEYS = {
    "adaptiveGroupSize", "adaptiveTier", "audioWire", "blocksWireMessages", "coordWindowPoint",
    "cursorShape", "cursorUpdate", "fecParity", "fecRecover", "fpsGovernorEwma", "fragmentEncode",
    "inputEvent", "metadataCodecPayloads", "metadataWireMessages", "muxBare", "muxEnvelopes",
    "muxFragment", "networkEstimateFold", "owdLateDrive", "pacerDepthFloats", "pacerDepthHinted",
    "recovery", "sizeNegotiationClamp", "sizeNegotiationEpoch", "staticIdrDrive", "swipeNavStatus",
    "systemDialogClassify", "systemDialogDetect", "terminalWireMessages", "trendlineDrive",
    "udpBackoff", "udpRearm", "videoControl", "windowGeometry", "workspaceIntentArgs",
    "workspaceIntentOps", "workspaceStateCodec", "workspaceWireMessages", "ycbcr",
}

# In the corpus, NOT emitted; pinned by their own XCTest suites. See the header before touching.
FROZEN_KEYS = {
    "captureRetarget", "captureUnion", "hostOutputSniffer", "inputMotionCoalesce", "naluJoin",
    "naluSplit", "terminalModeTracker", "vdChipPixelLimit", "vdOriginToRight", "vdRefreshRates",
    "virtualDisplayGeometry", "windowFits", "windowPlacement",
}

# Written out for the reader check below, so that gate reads THIS list rather than a copy of it.
open(sys.argv[3], "w").write("\n".join(sorted(FROZEN_KEYS)))

corpus = json.load(open(sys.argv[1]))
regen = json.load(open(sys.argv[2]))
canon = lambda x: json.dumps(x, sort_keys=True, separators=(",", ":"))

failures = []


def pin(label, expected, actual, gone, new):
    """Assert an exact key set, naming BOTH drift directions."""
    missing, extra = sorted(expected - actual), sorted(actual - expected)
    if missing:
        failures.append(f"{label}: {gone}: {missing}")
    if extra:
        failures.append(f"{label}: {new}: {extra}")


# A key in both buckets would make the corpus assertion pass while excusing a dropped emission.
overlap = sorted(EMITTED_KEYS & FROZEN_KEYS)
if overlap:
    failures.append(f"pin is self-inconsistent — both emitted and frozen: {overlap}")

pin(
    "generator", EMITTED_KEYS, set(regen),
    "pinned key NO LONGER EMITTED (add the emission back, or move it to FROZEN_KEYS with an "
    "XCTest that pins its bytes)",
    "emits UNPINNED key (hand-merge it into the corpus and add it to EMITTED_KEYS)",
)
pin(
    "corpus", EMITTED_KEYS | FROZEN_KEYS, set(corpus),
    "pinned key MISSING FROM THE CORPUS (a `>`-redirect over golden_vectors.json does this)",
    "holds UNPINNED key (add it to EMITTED_KEYS or FROZEN_KEYS)",
)

# Byte-diff over the keys actually present on both sides, so a set drift reports as a set drift
# rather than a KeyError. The pin above independently guarantees this covers all of EMITTED_KEYS.
diffed = sorted(EMITTED_KEYS & set(corpus) & set(regen))
bad = [k for k in diffed if canon(corpus[k]) != canon(regen[k])]
if bad:
    failures.append(f"DIVERGED bytes ({len(bad)}): {sorted(bad)}")

print(f"golden-check: {len(diffed)} emitted keys diffed vs {sys.argv[1]}")
if failures:
    for f in failures:
        print(f"  FAIL — {f}")
    sys.exit(1)
print("  PASS — all emitted keys byte-identical")
print(f"  ({len(FROZEN_KEYS)} frozen keys are suite-pinned, not emitted: {sorted(FROZEN_KEYS)})")
PY

# A frozen key is pinned by a SUITE, not by this list saying so. That sentence used to be the whole
# guarantee, and for ten of the thirteen it was false: `terminalModeTracker` was replayed by nothing,
# `inputMotionCoalesce` was not named anywhere in the repository, and the capture / virtual-display /
# window-placement keys were covered by a note in the generator claiming a `slopdesk_core` crate and a
# `golden_parity` test validated them — neither of which exists. Unread vectors do not stay true:
# `vdRefreshRates` had silently recorded a superseded law since `6281fae2` changed it.
#
# So the claim is checked. Every frozen key must be named by a file that READS the corpus — a Swift
# suite under `Tests/` or a Rust integration test under `rust/*/tests/` — and an emitted key needs no
# such reader, because regenerating and byte-diffing IS its pin.
#
# The reader must OPEN the corpus, not merely say the key's name: `VirtualDisplayGeometryTests`
# named three of these keys in `// MARK:` headings above hand-written assertions, which is exactly
# the shape that looks like coverage and is not. So a candidate file counts only if it also
# mentions `golden_vectors` or `GoldenCorpus`.
missing=()
while IFS= read -r key; do
  reader=""
  while IFS= read -r candidate; do
    if grep -ql -e 'golden_vectors' -e 'GoldenCorpus' "${candidate}"; then
      reader="${candidate}"
      break
    fi
  done < <(grep -rl -- "${key}" Tests rust/*/tests 2> /dev/null || true)
  [[ -n "${reader}" ]] || missing+=("${key}")
done < "${FROZEN_LIST}"
if [[ "${#missing[@]}" -gt 0 ]]; then
  printf 'golden-check: FAIL — frozen key with NO reader: %s\n' "${missing[*]}" >&2
  printf '  A frozen key is pinned by a suite that replays it, or it is not pinned at all.\n' >&2
  exit 1
fi
printf 'golden-check: every frozen key has a suite that replays it.\n'
