import Foundation

// The SEED HISTORY, lifted out of ``CodeServerManager``'s body. It is ~1300 lines of retired JSON
// that no reader of the manager's logic ever needs to scroll past, and its growth is what pushed
// the class over swiftlint's `type_body_length`. An extension is a separate declaration, so the
// history can keep growing here without crowding the type it belongs to.
extension CodeServerManager {
    /// Every seed this manager EVER shipped before the current one. A settings file byte-identical
    /// to a former seed is still PRISTINE — the user never touched it (the workbench rewrites the
    /// file on any settings edit) — so it may be upgraded to the current seed. Anything else is the
    /// user's and stays untouchable.
    static let obsoleteSeeds: [String] = [
        // v1 — theme + no welcome tab.
        """
        {
            "workbench.colorTheme": "Default Dark Modern",
            "workbench.startupEditor": "none"
        }
        """,
        // v2 — the lean pass (AI off, title-bar strips off), activity bar still its own column.
        """
        {
            "workbench.colorTheme": "Default Dark Modern",
            "workbench.startupEditor": "none",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false
        }
        """,
        // v3 — activity bar folded into the sidebar top, auxiliary sidebar pinned hidden.
        """
        {
            "workbench.colorTheme": "Default Dark Modern",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "top",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.customTitleBarVisibility": "never",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false
        }
        """,
        // v4 — auto-save on focus change; still the stock dark theme, sidebar still left.
        """
        {
            "workbench.colorTheme": "Default Dark Modern",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "top",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.customTitleBarVisibility": "never",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v5 — the SlopDesk Monokai theme + sidebar right; activity bar still folded into the
        // sidebar top, which force-showed the workbench title bar.
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.customTitleBarVisibility": "never",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v6 — the first chrome-less seed. Carried three keys the web workbench does not
        // REGISTER (chat.* — Code-OSS ships no chat; customTitleBarVisibility — desktop-only):
        // the settings editor flagged them as unknown in a file we authored.
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.customTitleBarVisibility": "never",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "window.density.editorTabHeight": "compact",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "ui-monospace, Menlo, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v6 as the WORKBENCH mutated it in the wild: with the theme extension invisible (the
        // empty-registry bug below), resolving the unknown theme dropped exactly the
        // `workbench.colorTheme` line — deterministic, observed byte-for-byte, so it is still
        // OUR file, not the user's.
        """
        {
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.customTitleBarVisibility": "never",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "window.density.editorTabHeight": "compact",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "chat.disableAIFeatures": true,
            "chat.commandCenter.enabled": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "ui-monospace, Menlo, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v7 — registered-keys-only, but the editor face was still `ui-monospace` (SF Mono in
        // WebKit) while the terminal actually renders libghostty's embedded JetBrains Mono —
        // "SF Mono" resolves on NEITHER machine, so the two monos never matched.
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "window.density.editorTabHeight": "compact",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "ui-monospace, Menlo, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v8 — JetBrains Mono + lineHeight 1.32 + per-client light/dark, but still the COMPACT tab
        // density: 22px tabs that the Slate plate recut (height − 8) squeezed to squat 14px
        // plates. v9 drops the density line (default 35px → 27px plates).
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "window.density.editorTabHeight": "compact",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v9 — full-height tab plates, but markdown still opened as raw source; v10 adds the
        // preview-first editor association.
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v10 — markdown preview-first, but editor tabs still wore the git-decoration letter
        // badge — the sub-baseline Added/Modified letter that reads as a stray character beside
        // the label; v11 turns tab badges off (the explorer keeps its own).
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v11 — tab badges off, but the activity bar was still fully HIDDEN: reaching Search /
        // Source Control / Extensions needed chords only. v12 folds the activity-bar icons into
        // the sidebar TOP instead (user-directed 2026-08-03).
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "hidden",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v12 — the activity bar folded into the sidebar top, but the editor gutter still spent a
        // five-char line-number reserve + glyph margin + folding arrows on emptiness. v13 slims
        // all three (user-directed 2026-08-03).
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v13 — the gutter slimmed, but the themes were still the "SlopDesk Monokai" derivations
        // (17 chrome-accent keys neutralized, plate tab fills). v14 ships the stock Monokai Pro
        // pair under their own names, seam borders retinted only (user-directed 2026-08-03).
        """
        {
            "workbench.colorTheme": "SlopDesk Monokai",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "SlopDesk Monokai",
            "workbench.preferredLightColorTheme": "SlopDesk Monokai Light",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.statusBar.visible": false,
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v14 — the stock Monokai Pro pair with the status bar back, but file icons were still the
        // workbench's minimal default. v15 selects the Material Icon Theme that
        // ``bundledMarketplaceExtensions`` installs (user-directed 2026-08-03).
        """
        {
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v15 — Material Icon Theme, but the reading aids were still the workbench's quiet
        // defaults. v16 turns on the structure guides (indentation pinned, active bracket pair,
        // sticky scroll, always-on tree guides with a deeper tree indent) and trailing-whitespace
        // rendering (user-directed 2026-08-04).
        """
        {
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v16 — carried a `window.title` template shaped for the panel strip's active-file readout.
        // The readout is gone (user-directed 2026-08-05: the workbench's own editor tab already
        // says which file is open), and with the web title bar clipped away client-side nothing
        // renders a title at all, so v17 drops the key back to the workbench's default.
        """
        {
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "window.title": "${dirty}${activeEditorShort}${separator}${rootName}",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v17 — the last seed written for a Code-OSS workbench with no chat in it. code-server
        // 4.113+ bundles the Copilot chat extension, which brings `chat.disableAIFeatures` back
        // into the schema (v7 had to drop it as unregistered), so v18 turns the AI surfaces off
        // again — the register this panel has always been seeded in.
        """
        {
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v20 — the pinned-dark seed: the split-tone Ember (dark glass beside light chrome)
        // dropped v19's `window.autoDetectColorScheme` trio so appearance-following could not
        // flip the glass light. The whole-app theme (user-directed 2026-08-07, polish round)
        // reversed that rationale — the client pins its WHOLE appearance to the theme polarity
        // and the webview inherits it — so v21 restored the trio, landing byte-identical to
        // v19. While v21 was the current seed, v19 could not sit in this list (the current seed
        // in the obsolete list would rewrite every font-synced host on each boot); now that the
        // current seed moved on, the v21 entry below covers pristine v19 files too.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Foundry Ember",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v21 — the whole-app-theme seed: restored the autoDetectColorScheme trio around the
        // Foundry Ember pair. v22 re-pointed the trio at the Dracula / Alucard pair (round-8
        // verdict, user-directed 2026-08-07); everything else is unchanged.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Foundry Ember",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Foundry Ember",
            "workbench.preferredLightColorTheme": "Foundry Ember Light",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v22 — the Dracula / Alucard trio (round-8 verdict). The current seed returns to the
        // v18 Monokai trio with the chrome revert (user-directed 2026-08-08), so the OLD v18
        // entry had to LEAVE this list — a seed byte-identical to the current one must never sit
        // here (the v19/v21 rule: the current seed in the obsolete list rewrites every
        // font-synced host on each boot).
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Dracula",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Dracula",
            "workbench.preferredLightColorTheme": "Alucard",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v23 — the Monokai trio as it stood before the workbench was asked to paint itself in
        // the app's own ground: the panel still wore the theme's own backdrop, so it read as a
        // second surface beside the navigator instead of the same continuous field
        // (user-directed 2026-08-08).
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v24 — the flat-cream seed, before selection was cut from the island. Every workbench
        // surface already stood on the ground cream, but the chosen row, tab and palette entry
        // still wore the theme's own selection wash, and the pair's drop shadows still smeared
        // the widgets that float over it (user-directed 2026-08-09).
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.activeBackground": "#FFFBEB",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v24 AS THE WORKBENCH LEFT IT — v24 with `chat.disableAIFeatures` REMOVED. Observed on
        // the live host: the running workbench rewrites this file on its own settings writes and
        // drops that key back out, the same class of machine mutation the v6-era entry above
        // records for `workbench.colorTheme`. Without this form a host that has ever had the
        // panel open reads as user-owned and can never be upgraded again, which is exactly how a
        // seed silently stops shipping.
        """
        {
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.activeBackground": "#FFFBEB",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v25 — the flat-shadow, island-selection seed while the workbench still wore Monokai.
        // v26 hands the editor to Alucard, whose published `editor.background` IS the app's
        // ground, and drops the appearance-flip trio the two-polarity Monokai pair needed
        // (user-directed 2026-08-09).
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Monokai Pro",
            "window.autoDetectColorScheme": true,
            "workbench.preferredDarkColorTheme": "Monokai Pro",
            "workbench.preferredLightColorTheme": "Monokai Pro Light",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "tab.activeBackground": "#22212C",
                "tab.activeForeground": "#F8F8F2",
                "tab.hoverBackground": "#22212C14",
                "list.activeSelectionBackground": "#22212C",
                "list.activeSelectionForeground": "#F8F8F2",
                "list.activeSelectionIconForeground": "#F8F8F2",
                "list.inactiveSelectionBackground": "#22212C",
                "list.inactiveSelectionForeground": "#F8F8F2",
                "list.inactiveSelectionIconForeground": "#F8F8F2",
                "list.focusBackground": "#22212C",
                "list.focusForeground": "#F8F8F2",
                "list.inactiveFocusBackground": "#22212C",
                "list.hoverBackground": "#22212C14",
                "list.focusOutline": "#00000000",
                "list.inactiveFocusOutline": "#00000000",
                "quickInputList.focusBackground": "#22212C",
                "quickInputList.focusForeground": "#F8F8F2",
                "quickInputList.focusIconForeground": "#F8F8F2",
                "editorSuggestWidget.selectedBackground": "#22212C",
                "editorSuggestWidget.selectedForeground": "#F8F8F2",
                "editorSuggestWidget.selectedIconForeground": "#F8F8F2",
                "menu.selectionBackground": "#22212C",
                "menu.selectionForeground": "#F8F8F2",
                "menu.selectionBorder": "#00000000",
                "widget.shadow": "#00000000",
                "scrollbar.shadow": "#00000000",
                "editorStickyScroll.shadow": "#00000000",
                "sideBarStickyScroll.shadow": "#00000000",
                "panelStickyScroll.shadow": "#00000000",
                "listFilterWidget.shadow": "#00000000",
                "welcomePage.tileShadow": "#00000000",
                "inlineChat.shadow": "#00000000",
                "diffEditor.unchangedRegionShadow": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v26 — the Alucard adoption, before the workbench's STRUCTURAL shadows were switched
        // off. Identical to the current seed but for `workbench.shadows`; retired the same day
        // it shipped, because the seam strips it leaves on the editor part's left and right
        // edges are drawn from stylesheet literals that no colour key in the block above can
        // reach.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.colorTheme": "Alucard",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "tab.activeBackground": "#22212C",
                "tab.activeForeground": "#F8F8F2",
                "tab.hoverBackground": "#22212C14",
                "list.activeSelectionBackground": "#22212C",
                "list.activeSelectionForeground": "#F8F8F2",
                "list.activeSelectionIconForeground": "#F8F8F2",
                "list.inactiveSelectionBackground": "#22212C",
                "list.inactiveSelectionForeground": "#F8F8F2",
                "list.inactiveSelectionIconForeground": "#F8F8F2",
                "list.focusBackground": "#22212C",
                "list.focusForeground": "#F8F8F2",
                "list.inactiveFocusBackground": "#22212C",
                "list.hoverBackground": "#22212C14",
                "list.focusOutline": "#00000000",
                "list.inactiveFocusOutline": "#00000000",
                "quickInputList.focusBackground": "#22212C",
                "quickInputList.focusForeground": "#F8F8F2",
                "quickInputList.focusIconForeground": "#F8F8F2",
                "editorSuggestWidget.selectedBackground": "#22212C",
                "editorSuggestWidget.selectedForeground": "#F8F8F2",
                "editorSuggestWidget.selectedIconForeground": "#F8F8F2",
                "menu.selectionBackground": "#22212C",
                "menu.selectionForeground": "#F8F8F2",
                "menu.selectionBorder": "#00000000",
                "widget.shadow": "#00000000",
                "scrollbar.shadow": "#00000000",
                "editorStickyScroll.shadow": "#00000000",
                "sideBarStickyScroll.shadow": "#00000000",
                "panelStickyScroll.shadow": "#00000000",
                "listFilterWidget.shadow": "#00000000",
                "welcomePage.tileShadow": "#00000000",
                "inlineChat.shadow": "#00000000",
                "diffEditor.unchangedRegionShadow": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v27 — Alucard with the structural shadows off, before selection stopped inverting
        // and before tabs were pinned to one width. Shipped to the live host on 2026-08-09 and
        // retired the same day; the file it left behind carries the workbench's own
        // `preferredLightColorTheme` write on top, which the machine-blind comparator absorbs.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.shadows": false,
            "workbench.colorTheme": "Alucard",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "tab.activeBackground": "#22212C",
                "tab.activeForeground": "#F8F8F2",
                "tab.hoverBackground": "#22212C14",
                "list.activeSelectionBackground": "#22212C",
                "list.activeSelectionForeground": "#F8F8F2",
                "list.activeSelectionIconForeground": "#F8F8F2",
                "list.inactiveSelectionBackground": "#22212C",
                "list.inactiveSelectionForeground": "#F8F8F2",
                "list.inactiveSelectionIconForeground": "#F8F8F2",
                "list.focusBackground": "#22212C",
                "list.focusForeground": "#F8F8F2",
                "list.inactiveFocusBackground": "#22212C",
                "list.hoverBackground": "#22212C14",
                "list.focusOutline": "#00000000",
                "list.inactiveFocusOutline": "#00000000",
                "quickInputList.focusBackground": "#22212C",
                "quickInputList.focusForeground": "#F8F8F2",
                "quickInputList.focusIconForeground": "#F8F8F2",
                "editorSuggestWidget.selectedBackground": "#22212C",
                "editorSuggestWidget.selectedForeground": "#F8F8F2",
                "editorSuggestWidget.selectedIconForeground": "#F8F8F2",
                "menu.selectionBackground": "#22212C",
                "menu.selectionForeground": "#F8F8F2",
                "menu.selectionBorder": "#00000000",
                "widget.shadow": "#00000000",
                "scrollbar.shadow": "#00000000",
                "editorStickyScroll.shadow": "#00000000",
                "sideBarStickyScroll.shadow": "#00000000",
                "panelStickyScroll.shadow": "#00000000",
                "listFilterWidget.shadow": "#00000000",
                "welcomePage.tileShadow": "#00000000",
                "inlineChat.shadow": "#00000000",
                "diffEditor.unchangedRegionShadow": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v28 — the flat panel at its FIRST tint ladder (12/8/5%) and the tab plate still on
        // the control radius. Shipped to the live host on 2026-08-09 and retired the same day:
        // the plate read too tight and too heavy at that dose.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.shadows": false,
            "workbench.colorTheme": "Alucard",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "tab.activeBackground": "#22212C1F",
                "tab.hoverBackground": "#22212C0D",
                "list.activeSelectionBackground": "#22212C1F",
                "list.inactiveSelectionBackground": "#22212C14",
                "list.focusBackground": "#22212C1F",
                "list.inactiveFocusBackground": "#22212C14",
                "list.hoverBackground": "#22212C0D",
                "list.focusOutline": "#00000000",
                "list.inactiveFocusOutline": "#00000000",
                "quickInputList.focusBackground": "#22212C1F",
                "editorSuggestWidget.selectedBackground": "#22212C1F",
                "menu.selectionBackground": "#22212C1F",
                "menu.selectionBorder": "#00000000",
                "widget.shadow": "#00000000",
                "scrollbar.shadow": "#00000000",
                "editorStickyScroll.shadow": "#00000000",
                "sideBarStickyScroll.shadow": "#00000000",
                "panelStickyScroll.shadow": "#00000000",
                "listFilterWidget.shadow": "#00000000",
                "welcomePage.tileShadow": "#00000000",
                "inlineChat.shadow": "#00000000",
                "diffEditor.unchangedRegionShadow": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "workbench.editor.tabSizing": "fixed",
            "workbench.editor.tabSizingFixedMinWidth": 140,
            "workbench.editor.tabSizingFixedMaxWidth": 140,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
        // v29 — the tint ladder at 9/6/4% while the tab strip still painted its INACTIVE
        // tabs in the ground colour. Shipped 2026-08-09 and retired the same day: fixed-width
        // slots that cannot be seen buy none of what fixed width is for.
        """
        {
            "chat.disableAIFeatures": true,
            "workbench.shadows": false,
            "workbench.colorTheme": "Alucard",
            "workbench.colorCustomizations": {
                "editor.background": "#FFFBEB",
                "editorGroup.emptyBackground": "#FFFBEB",
                "editorGroupHeader.noTabsBackground": "#FFFBEB",
                "welcomePage.background": "#FFFBEB",
                "editorGutter.background": "#FFFBEB",
                "editorStickyScroll.background": "#FFFBEB",
                "editorWidget.background": "#FFFBEB",
                "breadcrumb.background": "#FFFBEB",
                "sideBar.background": "#FFFBEB",
                "sideBar.border": "#00000000",
                "sideBarSectionHeader.background": "#FFFBEB",
                "sideBarSectionHeader.border": "#00000000",
                "activityBar.background": "#FFFBEB",
                "activityBar.border": "#00000000",
                "editorGroupHeader.tabsBackground": "#FFFBEB",
                "editorGroupHeader.tabsBorder": "#00000000",
                "editorGroupHeader.border": "#00000000",
                "editorGroup.border": "#00000000",
                "tab.inactiveBackground": "#FFFBEB",
                "tab.border": "#00000000",
                "tab.activeBackground": "#22212C17",
                "tab.hoverBackground": "#22212C0A",
                "list.activeSelectionBackground": "#22212C17",
                "list.inactiveSelectionBackground": "#22212C0F",
                "list.focusBackground": "#22212C17",
                "list.inactiveFocusBackground": "#22212C0F",
                "list.hoverBackground": "#22212C0A",
                "list.focusOutline": "#00000000",
                "list.inactiveFocusOutline": "#00000000",
                "quickInputList.focusBackground": "#22212C17",
                "editorSuggestWidget.selectedBackground": "#22212C17",
                "menu.selectionBackground": "#22212C17",
                "menu.selectionBorder": "#00000000",
                "widget.shadow": "#00000000",
                "scrollbar.shadow": "#00000000",
                "editorStickyScroll.shadow": "#00000000",
                "sideBarStickyScroll.shadow": "#00000000",
                "panelStickyScroll.shadow": "#00000000",
                "listFilterWidget.shadow": "#00000000",
                "welcomePage.tileShadow": "#00000000",
                "inlineChat.shadow": "#00000000",
                "diffEditor.unchangedRegionShadow": "#00000000",
                "panel.background": "#FFFBEB",
                "panel.border": "#00000000",
                "terminal.background": "#FFFBEB",
                "statusBar.background": "#FFFBEB",
                "statusBar.noFolderBackground": "#FFFBEB",
                "statusBar.border": "#00000000",
                "titleBar.activeBackground": "#FFFBEB",
                "titleBar.inactiveBackground": "#FFFBEB",
                "titleBar.border": "#00000000",
                "quickInput.background": "#FFFBEB",
                "menu.background": "#FFFBEB"
            },
            "workbench.iconTheme": "material-icon-theme",
            "workbench.startupEditor": "none",
            "workbench.editorAssociations": {
                "*.md": "vscode.markdown.preview.editor"
            },
            "workbench.activityBar.location": "top",
            "workbench.sideBar.location": "right",
            "workbench.secondarySideBar.defaultVisibility": "hidden",
            "window.menuBarVisibility": "hidden",
            "workbench.editor.empty.hint": "hidden",
            "workbench.editor.decorations.badges": false,
            "workbench.editor.tabSizing": "fixed",
            "workbench.editor.tabSizingFixedMinWidth": 140,
            "workbench.editor.tabSizingFixedMaxWidth": 140,
            "window.commandCenter": false,
            "workbench.layoutControl.enabled": false,
            "workbench.navigationControl.enabled": false,
            "workbench.tips.enabled": false,
            "extensions.ignoreRecommendations": true,
            "editor.minimap.enabled": false,
            "breadcrumbs.enabled": false,
            "editor.fontFamily": "'JetBrains Mono', ui-monospace, 'Symbols Nerd Font', monospace",
            "editor.fontSize": 13,
            "editor.lineHeight": 1.32,
            "editor.overviewRulerBorder": false,
            "editor.hideCursorInOverviewRuler": true,
            "editor.lineNumbersMinChars": 3,
            "editor.glyphMargin": false,
            "editor.folding": false,
            "editor.guides.indentation": true,
            "editor.guides.bracketPairs": "active",
            "editor.stickyScroll.enabled": true,
            "editor.renderWhitespace": "trailing",
            "workbench.tree.renderIndentGuides": "always",
            "workbench.tree.indent": 16,
            "files.autoSave": "onFocusChange"
        }
        """,
    ]
}
