//! `CHANGELOG.md`: rendering the whole file, and slicing one release out of it.
//!
//! ## The slice
//! The GitHub Release body is one section of this file. Before it, the body was nine fixed lines
//! that named an architecture and two brew commands, identical in every release — nothing in it
//! said which version it hung on, so opening `v0.2.1` and `v0.2.2` taught a reader the same
//! nothing. The changelog is generated from the commit log by git-cliff, so the notes cost nothing
//! per release and cannot drift from what actually shipped.
//!
//! A missing section is the release gate: the cut runs the slice before tagging, and the publish
//! job runs it before creating the Release, so a tag whose notes were never generated fails loudly
//! instead of shipping the fallback prose.
//!
//! ## The render, and the one byte it exists for
//! The body template in `cliff.toml` ends every release with a blank line so the next `## [x.y.z]`
//! heading is not glued to the previous release's last bullet, which leaves the final release
//! trailing that blank line at end-of-file. `end-of-file-fixer` (a pre-commit hook) then rewrites
//! the file — so the cut failed its own commit on a file it had generated seconds earlier, mid-cut,
//! with the six version sites already written.
//!
//! `postprocessors` in `cliff.toml` cannot fix it: they run per RELEASE, not over the finished
//! document, so a `\n+$` rule strips the separator from every body and glues the headings together
//! while leaving end-of-file exactly as it was. So the render goes through here, which is the ONLY
//! thing that may write `CHANGELOG.md`.

use std::fs;
use std::path::Path;

use crate::proc;

/// The rendered changelog's path, repo-relative.
pub const CHANGELOG: &str = "CHANGELOG.md";

/// The section of a rendered changelog that belongs to one version, blank-trimmed both ends.
///
/// git-cliff renders `## [0.2.3](compare-url) — 2026-08-11`. The match is on the bracketed version
/// alone: the date moves with the tag and the URL moves with the previous tag, so neither is safe
/// to anchor on — and it is a PREFIX test rather than a pattern, because the dots in a version are
/// regex wildcards and `0.2.3` would then also match a heading reading `0x2y3`.
#[must_use]
pub fn section(changelog: &str, version: &str) -> Option<String> {
    let wanted = format!("## [{}]", version.trim_start_matches('v'));
    let mut lines = changelog.lines();
    lines.find(|line| line.starts_with(&wanted))?;

    let body: Vec<&str> = lines.take_while(|line| !line.starts_with("## ")).collect();
    let first = body.iter().position(|line| !line.trim().is_empty())?;
    let last = body.iter().rposition(|line| !line.trim().is_empty())?;
    Some(body[first..=last].join("\n"))
}

/// Rewrite `CHANGELOG.md` from the commit log, passing `arguments` straight to git-cliff.
///
/// Rendered into memory rather than through `--output` so a git-cliff that fails leaves the
/// committed file untouched instead of truncated, and written with exactly one trailing newline.
///
/// # Errors
/// When git-cliff is absent, fails, or produces a document with nothing in it.
pub fn render(root: &Path, arguments: &[String]) -> Result<(), String> {
    if !proc::on_path("git-cliff") {
        return Err("render-changelog: git-cliff not on PATH (brew install git-cliff)".to_owned());
    }
    let rendered = proc::capture("git-cliff", arguments, root)?;
    if rendered.trim().is_empty() {
        return Err(
            "render-changelog: git-cliff produced an empty changelog — refusing to overwrite".to_owned(),
        );
    }
    fs::write(root.join(CHANGELOG), format!("{rendered}\n")).map_err(|error| format!("{CHANGELOG}: {error}"))
}

#[cfg(test)]
mod tests {
    use super::section;

    /// A raw string on purpose: `format_strings` rewraps a plain literal this wide, and rewrapping
    /// a fixture whose whitespace IS the thing under test silently rewrites the test.
    const RENDERED: &str = r"# Changelog

## [0.3.0](https://example/compare/v0.2.3...v0.3.0) — 2026-08-20

### Features

- add a pane

## [0.2.3](https://example/compare/v0.2.2...v0.2.3) — 2026-08-11

### Bug Fixes

- staple the ticket

<!-- generated by git-cliff -->
";

    #[test]
    fn a_section_stops_at_the_next_heading_and_carries_no_blank_edges() {
        assert_eq!(
            section(RENDERED, "0.3.0").as_deref(),
            Some("### Features\n\n- add a pane")
        );
    }

    #[test]
    fn the_last_section_runs_to_the_end_of_the_file() {
        assert_eq!(
            section(RENDERED, "0.2.3").as_deref(),
            Some("### Bug Fixes\n\n- staple the ticket\n\n<!-- generated by git-cliff -->")
        );
    }

    #[test]
    fn a_leading_v_is_not_part_of_the_heading() {
        assert_eq!(section(RENDERED, "v0.3.0"), section(RENDERED, "0.3.0"));
    }

    #[test]
    fn a_version_with_no_section_is_none() {
        assert_eq!(section(RENDERED, "0.9.9"), None);
    }

    /// The reason the match is a prefix test and not a regex: `.` is a wildcard.
    #[test]
    fn the_dots_in_a_version_are_not_wildcards() {
        let sneaky = "## [0x2y3](url) — 2026-01-01\n\n- nope\n";
        assert_eq!(section(sneaky, "0.2.3"), None);
    }

    #[test]
    fn a_section_with_nothing_in_it_is_none() {
        let empty = "## [0.1.0](url) — 2026-01-01\n\n\n## [0.0.9](url) — 2025-12-01\n\n- old\n";
        assert_eq!(section(empty, "0.1.0"), None);
    }
}
